name: PiggyAntiCheats
main: PiggyAntiCheats\Main
version: 1.0.0
api: [3.0.0-ALPHA5]
author: DaPigGuy
permissions:
  piggyanticheats:
    default: op
    description: "Allow using all PiggyAntiCheats features"
    children:
      piggyanticheats.notify:
        default: op
        description: "Get notifications from suspicion checks"