#                                      
#,-.----.                              
#\    /  \     ,---,         ,----..   
#|   :    \   '  .' \       /   /   \  
#|   |  .\ : /  ;    '.    |   :     : 
#.   :  |: |:  :       \   .   |  ;. / 
#|   |   \ ::  |   /\   \  .   ; /--`  
#|   : .   /|  :  ' ;.   : ;   | ;     
#;   | |`-' |  |  ;/  \   \|   : |     
#|   | ;    '  :  | \  \ ,'.   | '___  
#:   ' |    |  |  '  '--'  '   ; : .'| 
#:   : :    |  :  :        '   | '/  : 
#|   | :    |  | ,'        |   :    /  
#`---'.|    `--''           \   \ .'   
#  `---`                     `---`      

detection:
  #Speed needed to be detected (blocks per second)
  speed: 2
  #Blocks up needed to be detected (blocks per second)  
  jump: 2
  #Distance above ground to detect fly
  fly: 3
punishment:
  #How many points needed before a punishment
  points-til-punishment: 10
  #The punishment (kick, ban, ipban, none)
  punishment: kick   
message:
  #Language
  #Available Languages: eng
  lang: eng                                    